name: Build MSIX (Windows)

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        channel: stable

    - run: flutter pub get
    - run: flutter build windows

    - name: Decode certificate
      shell: powershell
      run: |
        echo "${{ secrets.WINDOWS_CERT }}" > cert.b64
        certutil -decode cert.b64 elmagnus.pfx

    - run: dart run msix:create
      env:
        MSIX_CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}

    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/windows/runner/Release/*.msix
        asset_name: EL-MAGNUS.msix
        asset_content_type: application/octet-stream

